import { Platform, StatusBar, StyleSheet } from "react-native";
import { COLORS } from "../theme/colors";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.bg,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight ?? 0 : 0,
  },
  screen: { flex: 1, backgroundColor: COLORS.bg },
  screenContent: { paddingHorizontal: 20, paddingBottom: 36, gap: 18 },
  detailContent: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 40, gap: 28 },
  loginScreen: {
    flex: 1,
    paddingHorizontal: 28,
    paddingVertical: 24,
    justifyContent: "space-between",
    backgroundColor: COLORS.bg,
  },
  loginHeader: { marginTop: 36, alignItems: "center", gap: 12 },
  logoWrap: { width: 108, height: 132, alignItems: "center", justifyContent: "center" },
  ear: {
    position: "absolute",
    top: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.yellowBright,
    borderWidth: 3,
    borderColor: "#ffecad",
  },
  earLeft: { left: 14 },
  earRight: { right: 14 },
  face: {
    width: 82,
    height: 82,
    borderRadius: 30,
    backgroundColor: COLORS.yellow,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "#ffecad",
    marginTop: 10,
  },
  glassesRow: { flexDirection: "row", alignItems: "center", marginTop: 2 },
  glass: { width: 18, height: 14, borderRadius: 5, borderWidth: 2, borderColor: COLORS.panelSoft },
  bridge: { width: 8, height: 2, backgroundColor: COLORS.panelSoft },
  eyeRow: { flexDirection: "row", gap: 16, marginTop: 10 },
  eye: { width: 6, height: 6, borderRadius: 3, backgroundColor: COLORS.panelSoft },
  nose: { width: 12, height: 10, borderRadius: 6, marginTop: 10, backgroundColor: "#d79e23" },
  whiskerRow: {
    position: "absolute",
    bottom: 18,
    width: 68,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  whiskerLeft: {
    width: 20,
    height: 2,
    backgroundColor: COLORS.panelSoft,
    transform: [{ rotate: "-12deg" }],
  },
  whiskerRight: {
    width: 20,
    height: 2,
    backgroundColor: COLORS.panelSoft,
    transform: [{ rotate: "12deg" }],
  },
  collar: {
    width: 40,
    height: 16,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    backgroundColor: "#f6f0df",
    marginTop: -4,
  },
  tie: {
    width: 16,
    height: 28,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    backgroundColor: COLORS.panelSoft,
    marginTop: -2,
  },
  brandTitle: { fontSize: 34, fontWeight: "800", color: COLORS.text },
  brandSubtitle: { fontSize: 20, color: COLORS.muted },
  formCard: { gap: 16 },
  input: {
    backgroundColor: COLORS.panelSoft,
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 18,
    fontSize: 20,
    color: COLORS.text,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  primaryButton: {
    backgroundColor: COLORS.yellow,
    paddingVertical: 18,
    borderRadius: 20,
    alignItems: "center",
    marginTop: 4,
    shadowColor: COLORS.yellow,
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
  },
  primaryButtonText: { color: COLORS.panelSoft, fontSize: 22, fontWeight: "800" },
  helperText: { color: COLORS.muted, fontSize: 15, textAlign: "center", lineHeight: 22 },
  footerLinks: { alignItems: "center", gap: 12, marginBottom: 18 },
  secondaryLink: { color: COLORS.yellowBright, fontSize: 18, fontWeight: "700" },
  signupText: { color: COLORS.muted, fontSize: 17 },
  signupAccent: { color: COLORS.yellowBright, fontWeight: "800" },
  searchRow: { marginTop: 12, flexDirection: "row", alignItems: "center", gap: 12 },
  searchShell: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.panelSoft,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 18,
    minHeight: 58,
  },
  searchInput: { flex: 1, color: COLORS.text, fontSize: 18 },
  avatarButton: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: COLORS.yellow,
    alignItems: "center",
    justifyContent: "center",
  },
  docsButton: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: COLORS.panel,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    justifyContent: "center",
  },
  docsIconPaper: {
    width: 24,
    height: 28,
    borderRadius: 6,
    backgroundColor: COLORS.yellowBright,
    paddingHorizontal: 5,
    paddingVertical: 6,
    gap: 4,
  },
  docsIconLineShort: {
    width: 10,
    height: 2,
    borderRadius: 999,
    backgroundColor: COLORS.panelSoft,
  },
  docsIconLine: {
    width: "100%",
    height: 2,
    borderRadius: 999,
    backgroundColor: COLORS.panelSoft,
  },
  avatarText: { color: COLORS.panelSoft, fontSize: 18, fontWeight: "900" },
  bannerCard: {
    backgroundColor: COLORS.panel,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 28,
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
  },
  bannerEyebrow: {
    color: COLORS.yellowBright,
    fontSize: 14,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  bannerTitle: { color: COLORS.text, fontSize: 26, fontWeight: "800", marginTop: 6 },
  bannerBody: { color: COLORS.muted, fontSize: 15, lineHeight: 22, marginTop: 8, maxWidth: 210 },
  categoryRow: { flexDirection: "row", gap: 10 },
  categoryChip: {
    flex: 1,
    backgroundColor: COLORS.panel,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
  },
  categoryChipActive: { backgroundColor: COLORS.yellowSoft, borderColor: "#73531b" },
  categoryChipText: { color: COLORS.yellowBright, fontSize: 14, fontWeight: "700", textAlign: "center" },
  categoryChipActiveText: { color: COLORS.yellowBright, fontSize: 14, fontWeight: "800", textAlign: "center" },
  sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 8 },
  sectionTitle: { color: COLORS.text, fontSize: 28, fontWeight: "800" },
  sectionMeta: { color: COLORS.muted, fontSize: 15 },
  searchResultsWrap: { gap: 14 },
  searchResultCard: {
    backgroundColor: COLORS.panel,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 14,
  },
  searchResultTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  searchResultTicker: {
    color: COLORS.text,
    fontSize: 24,
    fontWeight: "800",
  },
  searchResultCompany: {
    color: COLORS.muted,
    fontSize: 15,
    marginTop: 4,
  },
  searchResultBottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  searchResultMeta: {
    color: COLORS.yellowBright,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  searchResultHint: {
    color: COLORS.muted,
    fontSize: 13,
  },
  assetCard: {
    backgroundColor: COLORS.panel,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 18,
  },
  assetInfo: { flex: 1, gap: 18 },
  assetTopRow: { flexDirection: "row", justifyContent: "space-between", gap: 12 },
  assetTicker: { color: COLORS.text, fontSize: 28, fontWeight: "800" },
  assetCompany: { color: COLORS.muted, fontSize: 16, marginTop: 4 },
  assetTag: {
    alignSelf: "flex-start",
    backgroundColor: COLORS.panelSoft,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  assetTagText: { color: COLORS.yellowBright, fontSize: 12, fontWeight: "700" },
  assetBottomRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", gap: 12 },
  assetPrice: { color: COLORS.text, fontSize: 34, fontWeight: "800" },
  assetMove: { fontSize: 24, fontWeight: "800" },
  trendTrack: { alignItems: "flex-end", justifyContent: "center", minWidth: 44 },
  trendSegment: { height: 4, borderRadius: 999 },
  detailTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", zIndex: 2 },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: COLORS.panel,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
  },
  backButtonText: { color: COLORS.text, fontSize: 26, fontWeight: "700", marginTop: -2 },
  marketOpenWrap: { flexDirection: "row", alignItems: "center", gap: 8 },
  marketDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.success },
  marketOpenText: { color: COLORS.success, fontSize: 16, fontWeight: "700" },
  detailHeader: { gap: 8 },
  detailCompany: { color: COLORS.text, fontSize: 34, fontWeight: "800" },
  detailMetaRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  detailTicker: { color: COLORS.muted, fontSize: 22 },
  stockPill: {
    backgroundColor: COLORS.yellowSoft,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: "#73531b",
  },
  stockPillText: { color: COLORS.yellowBright, fontSize: 13, fontWeight: "700" },
  detailPrice: { color: COLORS.text, fontSize: 52, fontWeight: "800", marginTop: 10 },
  detailChange: { fontSize: 18, fontWeight: "700" },
  sectionBlock: { gap: 16 },
  detailSectionTitle: { color: COLORS.text, fontSize: 24, fontWeight: "800" },
  detailSubtext: { color: COLORS.muted, fontSize: 13, lineHeight: 18 },
  detailSubtextLive: { color: COLORS.success },
  detailSubtextFallback: { color: COLORS.yellowBright },
  holdersCard: {
    backgroundColor: COLORS.panel,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 16,
    paddingVertical: 22,
    alignItems: "center",
    gap: 18,
  },
  holdersChartWrap: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 220,
  },
  holdingsSummaryRow: {
    width: "100%",
    flexDirection: "row",
    gap: 12,
  },
  holdingsSummaryChip: {
    flex: 1,
    backgroundColor: COLORS.panelSoft,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  holdingsSummaryLabel: {
    color: COLORS.muted,
    fontSize: 12,
  },
  holdingsSummaryValue: {
    color: COLORS.text,
    fontSize: 18,
    fontWeight: "800",
    marginTop: 6,
  },
  holdingsAsOf: {
    color: COLORS.muted,
    fontSize: 12,
    alignSelf: "flex-start",
  },
  holdersLegend: {
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 14,
    rowGap: 10,
  },
  holdersLegendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  holdersLegendSwatch: {
    width: 14,
    height: 14,
    borderRadius: 3,
  },
  holdersLegendText: {
    color: COLORS.text,
    fontSize: 12,
  },
  topHoldingsList: {
    width: "100%",
    gap: 12,
  },
  topHoldingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.panelSoft,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  topHoldingLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flexShrink: 1,
  },
  topHoldingRank: {
    color: COLORS.muted,
    fontSize: 13,
    width: 18,
  },
  topHoldingSymbol: {
    color: COLORS.text,
    fontSize: 15,
    fontWeight: "800",
  },
  topHoldingName: {
    color: COLORS.muted,
    fontSize: 12,
    marginTop: 2,
  },
  topHoldingWeight: {
    color: COLORS.yellowBright,
    fontSize: 15,
    fontWeight: "800",
  },
  metricsSearchWrap: {
    backgroundColor: COLORS.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 16,
    minHeight: 56,
    justifyContent: "center",
  },
  metricsSearchInput: {
    color: COLORS.text,
    fontSize: 16,
  },
  metricsSearchResults: {
    gap: 10,
  },
  metricSearchItem: {
    backgroundColor: COLORS.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  metricSearchLabel: {
    color: COLORS.text,
    fontSize: 15,
    fontWeight: "700",
  },
  metricSearchValue: {
    color: COLORS.yellowBright,
    fontSize: 14,
    fontWeight: "700",
  },
  metricChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  metricChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.yellowSoft,
    borderWidth: 1,
    borderColor: "#73531b",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  metricChipText: {
    color: COLORS.yellowBright,
    fontSize: 14,
    fontWeight: "800",
  },
  metricChipClose: {
    color: COLORS.text,
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 18,
  },
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
  },
  metricCard: {
    width: "47%",
    backgroundColor: COLORS.panel,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 18,
    gap: 16,
  },
  metricCardTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  metricCardLabel: {
    color: COLORS.muted,
    fontSize: 16,
  },
  metricInfoIcon: {
    color: COLORS.yellowBright,
    fontSize: 14,
    fontWeight: "800",
  },
  metricCardValue: {
    color: COLORS.text,
    fontSize: 28,
    fontWeight: "800",
  },
  metricModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(3, 6, 14, 0.78)",
    justifyContent: "center",
    paddingHorizontal: 22,
  },
  metricModalCard: {
    maxHeight: "78%",
    backgroundColor: COLORS.panel,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 22,
    paddingVertical: 20,
  },
  metricModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
    marginBottom: 16,
  },
  metricModalTitle: {
    color: COLORS.text,
    fontSize: 22,
    fontWeight: "800",
  },
  metricModalValue: {
    color: COLORS.yellowBright,
    fontSize: 20,
    fontWeight: "800",
    marginTop: 10,
  },
  metricModalClose: {
    color: COLORS.muted,
    fontSize: 26,
    fontWeight: "700",
    lineHeight: 26,
  },
  metricModalSection: {
    marginBottom: 18,
    gap: 8,
  },
  metricModalSectionLabel: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  metricModalBody: {
    color: COLORS.text,
    fontSize: 16,
    lineHeight: 24,
  },
  metricFormulaBox: {
    backgroundColor: COLORS.panelSoft,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  metricFormulaText: {
    color: COLORS.text,
    fontSize: 16,
    lineHeight: 22,
  },
  guideContent: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 40, gap: 24 },
  guideHeader: { gap: 8 },
  guideCard: {
    backgroundColor: COLORS.panel,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 10,
  },
  guideCardTitle: {
    color: COLORS.text,
    fontSize: 18,
    fontWeight: "800",
  },
  guideCardBody: {
    color: COLORS.muted,
    fontSize: 15,
    lineHeight: 23,
  },
  guideGuideLabel: {
    color: COLORS.yellowBright,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginTop: 2,
  },
  guideTipRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  guideTipIndex: {
    color: COLORS.yellowBright,
    fontSize: 15,
    fontWeight: "800",
    minWidth: 16,
  },
  guideTipText: {
    flex: 1,
    color: COLORS.text,
    fontSize: 15,
    lineHeight: 23,
  },
  chartCard: {
    backgroundColor: COLORS.panel,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 16,
    paddingTop: 22,
    paddingBottom: 18,
    gap: 18,
  },
  chartEmptyState: {
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    gap: 10,
  },
  chartEmptyTitle: {
    color: COLORS.text,
    fontSize: 20,
    fontWeight: "800",
    textAlign: "center",
  },
  chartEmptyBody: {
    color: COLORS.muted,
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  chartArea: { flexDirection: "row", gap: 10 },
  chartYAxis: { justifyContent: "space-between", paddingTop: 6, paddingBottom: 30 },
  chartAxisLabel: { color: COLORS.muted, fontSize: 12 },
  chartBody: { flex: 1, minHeight: 280 },
  chartGrid: { position: "absolute", left: 0, right: 0, height: 1, backgroundColor: "#1a2234" },
  chartSvgShell: { height: 220, position: "relative", overflow: "hidden", marginTop: 4 },
  chartLabelsRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 12 },
  chartXLabel: { color: COLORS.muted, fontSize: 11 },
  rangeRow: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  rangeChip: {
    backgroundColor: COLORS.panelSoft,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
  },
  rangeChipActive: { backgroundColor: COLORS.yellow, borderColor: COLORS.yellow },
  rangeChipText: { color: COLORS.text, fontSize: 15, fontWeight: "700" },
  rangeChipTextActive: { color: COLORS.panelSoft },
});
