const QUOTE_SOURCES = {
  TSLA: {
    symbol: "TSLA",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-tsla-price-page",
    parser: "marketcap",
  },
  AAPL: {
    symbol: "AAPL",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-aapl-price-page",
    parser: "marketcap",
  },
  NVDA: {
    symbol: "NVDA",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-nvda-price-page",
    parser: "marketcap",
  },
  MSFT: {
    symbol: "MSFT",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-msft-price-page",
    parser: "marketcap",
  },
  AMZN: {
    symbol: "AMZN",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-amzn-price-page",
    parser: "marketcap",
  },
  GOOGL: {
    symbol: "GOOGL",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-googl-price-page",
    parser: "marketcap",
  },
  META: {
    symbol: "META",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-meta-price-page",
    parser: "marketcap",
  },
  AVGO: {
    symbol: "AVGO",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-avgo-price-page",
    parser: "marketcap",
  },
  AMD: {
    symbol: "AMD",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-amd-price-page",
    parser: "marketcap",
  },
  NFLX: {
    symbol: "NFLX",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-nflx-price-page",
    parser: "marketcap",
  },
  ORCL: {
    symbol: "ORCL",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-orcl-price-page",
    parser: "marketcap",
  },
  JPM: {
    symbol: "JPM",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-jpm-price-page",
    parser: "marketcap",
  },
  BAC: {
    symbol: "BAC",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-bac-price-page",
    parser: "marketcap",
  },
  WMT: {
    symbol: "WMT",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-wmt-price-page",
    parser: "marketcap",
  },
  COST: {
    symbol: "COST",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-cost-price-page",
    parser: "marketcap",
  },
  LLY: {
    symbol: "LLY",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-lly-price-page",
    parser: "marketcap",
  },
  XOM: {
    symbol: "XOM",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-xom-price-page",
    parser: "marketcap",
  },
  JNJ: {
    symbol: "JNJ",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-jnj-price-page",
    parser: "marketcap",
  },
  KO: {
    symbol: "KO",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-ko-price-page",
    parser: "marketcap",
  },
  SPY: {
    symbol: "SPY",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-spy-page",
    parser: "marketcap",
  },
  VGT: {
    symbol: "VGT",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-vgt-page",
    parser: "marketcap",
  },
  QQQ: {
    symbol: "QQQ",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-qqq-page",
    parser: "etfOverviewQuote",
  },
  VOO: {
    symbol: "VOO",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-voo-page",
    parser: "etfOverviewQuote",
  },
  IVV: {
    symbol: "IVV",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-ivv-page",
    parser: "etfOverviewQuote",
  },
  DIA: {
    symbol: "DIA",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-dia-page",
    parser: "etfOverviewQuote",
  },
  IWM: {
    symbol: "IWM",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-iwm-page",
    parser: "etfOverviewQuote",
  },
  XLK: {
    symbol: "XLK",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-xlk-page",
    parser: "etfOverviewQuote",
  },
  XLF: {
    symbol: "XLF",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-xlf-page",
    parser: "etfOverviewQuote",
  },
  XLV: {
    symbol: "XLV",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-xlv-page",
    parser: "etfOverviewQuote",
  },
  VTI: {
    symbol: "VTI",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-vti-page",
    parser: "etfOverviewQuote",
  },
  SMH: {
    symbol: "SMH",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-smh-page",
    parser: "etfOverviewQuote",
  },
  GOLD: {
    symbol: "GOLD",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-gold-page",
    parser: "commodity",
    commodityName: "gold",
  },
  SILVER: {
    symbol: "SILVER",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-silver-page",
    parser: "commodity",
    commodityName: "silver",
  },
  PALLADIUM: {
    symbol: "PALLADIUM",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-palladium-page",
    parser: "commodity",
    commodityName: "palladium",
  },
  PLATINUM: {
    symbol: "PLATINUM",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-platinum-page",
    parser: "commodity",
    commodityName: "platinum",
  },
  COPPER: {
    symbol: "COPPER",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-copper-page",
    parser: "commodityTradingEconomics",
    commodityName: "copper",
  },
  NICKEL: {
    symbol: "NICKEL",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-nickel-page",
    parser: "commodityTradingEconomics",
    commodityName: "nickel",
  },
  LITHIUM: {
    symbol: "LITHIUM",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-lithium-page",
    parser: "commodityTradingEconomics",
    commodityName: "lithium",
  },
  URANIUM: {
    symbol: "URANIUM",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-uranium-page",
    parser: "commodityTradingEconomics",
    commodityName: "uranium",
  },
  COBALT: {
    symbol: "COBALT",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-cobalt-page",
    parser: "commodityTradingEconomics",
    commodityName: "cobalt",
  },
  ZINC: {
    symbol: "ZINC",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-zinc-page",
    parser: "commodityTradingEconomics",
    commodityName: "zinc",
  },
};

const METRIC_SOURCES = {
  TSLA: {
    symbol: "TSLA",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-tsla-metrics-page",
    parser: "stockStatistics",
  },
  AAPL: {
    symbol: "AAPL",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-aapl-metrics-page",
    parser: "stockStatistics",
  },
  NVDA: {
    symbol: "NVDA",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-nvda-metrics-page",
    parser: "stockStatistics",
  },
  MSFT: {
    symbol: "MSFT",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-msft-metrics-page",
    parser: "stockStatistics",
  },
  AMZN: {
    symbol: "AMZN",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-amzn-metrics-page",
    parser: "stockStatistics",
  },
  GOOGL: {
    symbol: "GOOGL",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-googl-metrics-page",
    parser: "stockStatistics",
  },
  META: {
    symbol: "META",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-meta-metrics-page",
    parser: "stockStatistics",
  },
  AVGO: {
    symbol: "AVGO",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-avgo-metrics-page",
    parser: "stockStatistics",
  },
  AMD: {
    symbol: "AMD",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-amd-metrics-page",
    parser: "stockStatistics",
  },
  NFLX: {
    symbol: "NFLX",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-nflx-metrics-page",
    parser: "stockStatistics",
  },
  ORCL: {
    symbol: "ORCL",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-orcl-metrics-page",
    parser: "stockStatistics",
  },
  JPM: {
    symbol: "JPM",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-jpm-metrics-page",
    parser: "stockStatistics",
  },
  BAC: {
    symbol: "BAC",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-bac-metrics-page",
    parser: "stockStatistics",
  },
  WMT: {
    symbol: "WMT",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-wmt-metrics-page",
    parser: "stockStatistics",
  },
  COST: {
    symbol: "COST",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-cost-metrics-page",
    parser: "stockStatistics",
  },
  LLY: {
    symbol: "LLY",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-lly-metrics-page",
    parser: "stockStatistics",
  },
  XOM: {
    symbol: "XOM",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-xom-metrics-page",
    parser: "stockStatistics",
  },
  JNJ: {
    symbol: "JNJ",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-jnj-metrics-page",
    parser: "stockStatistics",
  },
  KO: {
    symbol: "KO",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-ko-metrics-page",
    parser: "stockStatistics",
  },
  SPY: {
    symbol: "SPY",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-spy-metrics-page",
    parser: "etfOverview",
  },
  VGT: {
    symbol: "VGT",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-vgt-metrics-page",
    parser: "etfOverview",
  },
  QQQ: {
    symbol: "QQQ",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-qqq-metrics-page",
    parser: "etfOverview",
  },
  VOO: {
    symbol: "VOO",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-voo-metrics-page",
    parser: "etfOverview",
  },
  IVV: {
    symbol: "IVV",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-ivv-metrics-page",
    parser: "etfOverview",
  },
  DIA: {
    symbol: "DIA",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-dia-metrics-page",
    parser: "etfOverview",
  },
  IWM: {
    symbol: "IWM",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-iwm-metrics-page",
    parser: "etfOverview",
  },
  XLK: {
    symbol: "XLK",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-xlk-metrics-page",
    parser: "etfOverview",
  },
  XLF: {
    symbol: "XLF",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-xlf-metrics-page",
    parser: "etfOverview",
  },
  XLV: {
    symbol: "XLV",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-xlv-metrics-page",
    parser: "etfOverview",
  },
  VTI: {
    symbol: "VTI",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-vti-metrics-page",
    parser: "etfOverview",
  },
  SMH: {
    symbol: "SMH",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-smh-metrics-page",
    parser: "etfOverview",
  },
  GOLD: {
    symbol: "GOLD",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-gold-metrics-page",
    parser: "commodityOverview",
    commodityName: "gold",
  },
  SILVER: {
    symbol: "SILVER",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-silver-metrics-page",
    parser: "commodityOverview",
    commodityName: "silver",
  },
  PALLADIUM: {
    symbol: "PALLADIUM",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-palladium-metrics-page",
    parser: "commodityOverview",
    commodityName: "palladium",
  },
  PLATINUM: {
    symbol: "PLATINUM",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-platinum-metrics-page",
    parser: "commodityOverview",
    commodityName: "platinum",
  },
  COPPER: {
    symbol: "COPPER",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-copper-metrics-page",
    parser: "commodityTradingEconomicsOverview",
    commodityName: "copper",
  },
  NICKEL: {
    symbol: "NICKEL",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-nickel-metrics-page",
    parser: "commodityTradingEconomicsOverview",
    commodityName: "nickel",
  },
  LITHIUM: {
    symbol: "LITHIUM",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-lithium-metrics-page",
    parser: "commodityTradingEconomicsOverview",
    commodityName: "lithium",
  },
  URANIUM: {
    symbol: "URANIUM",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-uranium-metrics-page",
    parser: "commodityTradingEconomicsOverview",
    commodityName: "uranium",
  },
  COBALT: {
    symbol: "COBALT",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-cobalt-metrics-page",
    parser: "commodityTradingEconomicsOverview",
    commodityName: "cobalt",
  },
  ZINC: {
    symbol: "ZINC",
    type: "metal",
    source: "scraped-web",
    url: "https://example.com/path-to-zinc-metrics-page",
    parser: "commodityTradingEconomicsOverview",
    commodityName: "zinc",
  },
};

const HOLDER_SOURCES = {
  TSLA: {
    symbol: "TSLA",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-tsla-holders-page",
    parser: "institutionalArticleListA",
  },
  AAPL: {
    symbol: "AAPL",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-aapl-holders-page",
    parser: "institutionalArticleTableB",
  },
  NVDA: {
    symbol: "NVDA",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-nvda-holders-page",
    parser: "institutionalArticleListC",
  },
  MSFT: {
    symbol: "MSFT",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-msft-holders-page",
    parser: "institutionalArticleTableC",
  },
  AMZN: {
    symbol: "AMZN",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-amzn-holders-page",
    parser: "rankredInstitutionalTable",
  },
  GOOGL: {
    symbol: "GOOGL",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-googl-holders-page",
    parser: "rankredInstitutionalTable",
  },
  META: {
    symbol: "META",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-meta-holders-page",
    parser: "institutionalArticleTableC",
  },
  NFLX: {
    symbol: "NFLX",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-nflx-holders-page",
    parser: "rankredInstitutionalTable",
  },
  ORCL: {
    symbol: "ORCL",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-orcl-holders-page",
    parser: "rankredInstitutionalTable",
  },
  WMT: {
    symbol: "WMT",
    type: "stock",
    source: "scraped-web",
    url: "https://example.com/path-to-wmt-holders-page",
    parser: "rankredInstitutionalTable",
  },
  SPY: {
    symbol: "SPY",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-spy-holdings-page",
    parser: "fundConstituentsTable",
  },
  VGT: {
    symbol: "VGT",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-vgt-holdings-page",
    parser: "fundConstituentsTable",
  },
  QQQ: {
    symbol: "QQQ",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-qqq-holdings-page",
    parser: "fundConstituentsTable",
  },
  VOO: {
    symbol: "VOO",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-voo-holdings-page",
    parser: "fundConstituentsTable",
  },
  IVV: {
    symbol: "IVV",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-ivv-holdings-page",
    parser: "fundConstituentsTable",
  },
  DIA: {
    symbol: "DIA",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-dia-holdings-page",
    parser: "fundConstituentsTable",
  },
  IWM: {
    symbol: "IWM",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-iwm-holdings-page",
    parser: "fundConstituentsTable",
  },
  XLK: {
    symbol: "XLK",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-xlk-holdings-page",
    parser: "fundConstituentsTable",
  },
  XLF: {
    symbol: "XLF",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-xlf-holdings-page",
    parser: "fundConstituentsTable",
  },
  XLV: {
    symbol: "XLV",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-xlv-holdings-page",
    parser: "fundConstituentsTable",
  },
  VTI: {
    symbol: "VTI",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-vti-holdings-page",
    parser: "fundConstituentsTable",
  },
  SMH: {
    symbol: "SMH",
    type: "etf",
    source: "scraped-web",
    url: "https://example.com/path-to-smh-holdings-page",
    parser: "fundConstituentsTable",
  },
};

module.exports = {
  QUOTE_SOURCES,
  METRIC_SOURCES,
  HOLDER_SOURCES,
};
